# Generated by Django 6.0.4 on 2026-05-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('14:00', '02:00 PM'), ('15:00', '03:00 PM'), ('16:00', '04:00 PM'), ('17:00', '05:00 PM')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, choices=[('below_5', 'Below ₹5 Lakhs'), ('5_10', '₹5 – ₹10 Lakhs'), ('10_25', '₹10 – ₹25 Lakhs'), ('25_50', '₹25 – ₹50 Lakhs'), ('above_50', 'Above ₹50 Lakhs')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=20)),
                ('source', models.CharField(default='website', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('price_starting', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_unit', models.CharField(default='per sq.ft', max_length=50)),
                ('inclusions', models.TextField(help_text='Comma-separated list')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('interiors', 'Interiors'), ('construction', 'Construction'), ('flooring', 'Flooring'), ('kitchen', 'Modular Kitchen'), ('outdoor', 'Outdoor')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='projects/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='projects/after/')),
                ('video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('service_type', models.CharField(max_length=100)),
                ('area_sqft', models.PositiveIntegerField()),
                ('style', models.CharField(blank=True, max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('interior', 'Interior Design & Execution'), ('flooring', 'Flooring Solutions'), ('construction', 'Construction & Architecture'), ('outdoor', 'Outdoor & Utility Services'), ('consultation', 'Planning & Consultation')], max_length=50)),
                ('description', models.TextField()),
                ('short_desc', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=10)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('slug', models.SlugField(unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
