# Generated by Django 5.2 on 2026-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/'),
        ),
    ]
